//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrabajoMovilesEntities : DbContext
    {
        public TrabajoMovilesEntities()
            : base("name=TrabajoMovilesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avance> avances { get; set; }
        public virtual DbSet<curso> cursoes { get; set; }
        public virtual DbSet<gradoescolar> gradoescolars { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<mensaje> mensajes { get; set; }
        public virtual DbSet<padre> padres { get; set; }
        public virtual DbSet<profesor> profesors { get; set; }
        public virtual DbSet<profesor_curso> profesor_curso { get; set; }
        public virtual DbSet<profesor_gradoescolar> profesor_gradoescolar { get; set; }
        public virtual DbSet<profesor_horario> profesor_horario { get; set; }
        public virtual DbSet<profesor_zona> profesor_zona { get; set; }
        public virtual DbSet<profesorfavorito> profesorfavoritoes { get; set; }
        public virtual DbSet<suscripcion> suscripcions { get; set; }
        public virtual DbSet<tutoria> tutorias { get; set; }
        public virtual DbSet<zona> zonas { get; set; }
    }
}
