//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int idmensaje { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string contenido { get; set; }
        public Nullable<int> id_padre { get; set; }
        public Nullable<int> id_profe { get; set; }
        public string remitente { get; set; }
    
        public virtual padre padre { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
