//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class metodopago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metodopago()
        {
            this.profesors = new HashSet<profesor>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string numerotarjeta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string cvv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesor> profesors { get; set; }
    }
}
