//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor_horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor_horario()
        {
            this.tutorias = new HashSet<tutoria>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> id_horario { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual profesor profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tutoria> tutorias { get; set; }
    }
}
