//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor_cursogrado
    {
        public int id { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> id_cursogrado { get; set; }
    
        public virtual cursogrado cursogrado { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
