//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuevosAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tutoria()
        {
            this.hijoes = new HashSet<hijo>();
            this.resumenclases = new HashSet<resumenclase>();
        }
    
        public int idtutoria { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string comentario { get; set; }
        public Nullable<int> calificacion { get; set; }
        public Nullable<int> id_padre { get; set; }
        public string estado { get; set; }
        public string curso { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> numerohoras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hijo> hijoes { get; set; }
        public virtual padre padre { get; set; }
        public virtual profesor_horario profesor_horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resumenclase> resumenclases { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
